//created on: Aug 11, 2017
package com.anthem.tat.retro
import com.anthem.tat.DTO.*;
import com.anthem.tat.xom.*;


//list any import classes here.



//declare any global variables here




 
global MemberFactshandlerClient memberservice;
salience 98;
agenda-group "AuthType"
no-loop
lock-on-active
rule "Determine if IP Concurrrent"
    when
       $member: MemberDTO(memberid!=null && authType!='Retro IP' && authType!='Preservice IP' && (umsvSeqNo!='0' || umsvSeqNo!='1'));
   
       
    then
        System.out.println("The member is Concurrrent");
        
         $member.setAuthType("Concurrent IP");
         memberservice.add($member);
         
         update($member);
         
   

end

