//created on: Aug 11, 2017
package com.anthem.tat.retro
import com.anthem.tat.DTO.*;
import com.anthem.tat.xom.*;



//list any import classes here.



//declare any global variables here


 
global MemberFactshandlerClient memberservice;

salience 96;
agenda-group "Extension"
no-loop
lock-on-active
rule "Determine if Concurrent Extension"
    when
      $member: MemberDTO(memberid!=null && authType=="Concurrent IP" && extRequested=="Y" && extdenied=="N");
  
       
    then
        System.out.println("The member is Concurrent IP Extension" );
        
         $member.setAuthType("Concurrent Extension IP");
         memberservice.add($member);
         
         //update($member);
         
            System.out.println("The member is Concurrent IP Extension" +  $member.getAuthType());
     

end
