//created on: Aug 11, 2017
package com.anthem.tat.retro
import com.anthem.tat.DTO.*;
import com.anthem.tat.xom.*;



//list any import classes here.



//declare any global variables here


 
global MemberFactshandlerClient memberservice;

salience 93;
agenda-group "Expedite"
no-loop
lock-on-active
rule "Determine if PreserviceExpedite2"
    when
      $member: MemberDTO(memberid!=null && authType=='Preservice IP' &&  ( meetexpedite==null && expeditereq==null));
       eval(memberservice.checkUmvtReasonCodeExists($member,"CO16","IN03","SR13","UP27","UP36","UP37","UP38","UP39","UP40","UP41") );
  
       
    then
        System.out.println("The member is Preservice Extension IP Expedite" );
        
         $member.setAuthType("Preservice IP Expedite");
         memberservice.add($member);
         
         //update($member);
         
            System.out.println("The member is Preservice Extension IP Expedite" +  $member.getAuthType());
     

end
